[tool.poetry]
name = "module3"
version = "0.1.0"
description = ""
authors = ["Terinor <kirstruk01@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
py7zr = "^0.20.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
